# Generated by Django 5.2.16 on 2026-07-20 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="projects.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["project", "-created_at"], name="idx_comment_project"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["author"], name="idx_comment_author"),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(fields=["project"], name="idx_projectfile_project"),
        ),
        migrations.AddIndex(
            model_name="projectfile",
            index=models.Index(fields=["file_type"], name="idx_projectfile_type"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="idx_project_owner_status"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["visibility", "status"], name="idx_project_vis_status"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["-created_at"], name="idx_project_created"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["title"], name="idx_project_title"),
        ),
    ]
