version: "3.9"
# 4 services
services:
  django:
    build: . # creating container base on dockerfile inthis directory
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app  # for hot reloading
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres: # if postgres and redis not ready djangowon't start
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data # database directory
    environment: # used in .env
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker: # heavy process in the background
    build: .
    command: celery -A config worker -l info
    volumes:
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - django

  celery_beat: # scheduling and ordeing worker
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - django

volumes:
  redis_data:
  postgres_data:
  static_volume:
  media_volume:
